#!/usr/bin/env bun
//MISE raw=true

import { once } from "node:events";
import html from "../index.html";

await using _child = Bun.spawn(["elm-watch", "hot"], {
	stdout: "inherit",
	stderr: "inherit",
});

using _server = Bun.serve({
	static: {
		"/": html,
	},
	development: {
		hmr: false,
	},
	fetch() {
		return new Response(null, { status: 404 });
	},
});

await once(process, "SIGTERM");
